---
abstract: 'Set of LEGO Color data'
author:
  - 'Avi Finkel <avi@finkel.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LEGO-Colors
no_index:
  directory:
    - inc
    - t
requires:
  Pod::Coverage: 0.18
  Test::Pod: 1.26
  Test::Pod::Coverage: 1.08
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: '0.4'
